export { Home } from './Home';
export { Notes } from './Notes';
export { Archived } from './Archived';
export { Deleted } from './Deleted';
export { Landing } from './Landing';
export { MockmanTest } from './MockmanTest';
export { Login } from './Login';
export { Signup } from './Signup';
export { Profile } from './Profile';
